import {
    AlertTriangle,
    ArrowDownLeft,
    ArrowLeftRight,
    ArrowUpRight,
    BadgeDollarSign,
    BadgePercent,
    Banknote,
    BarChart3,
    Barcode,
    Bell,
    Box,
    Boxes,
    Brush,
    Building2,
    Bus,
    CalendarCheck,
    CalendarClock,
    Calculator,
    Car,
    CheckCheck,
    CircleAlert,
    CircleCheckBig,
    CircleDot,
    CircleX,
    Cog,
    Coins,
    Contact,
    Container,
    Copy,
    Cpu,
    Droplets,
    Factory,
    FileClock,
    FileSignature,
    FileStack,
    FileText,
    FlaskRound,
    FolderOpen,
    Fuel,
    Gauge,
    GitBranch,
    Hammer,
    Hash,
    History,
    Image,
    IndianRupee,
    Landmark,
    Layers,
    LayoutDashboard,
    LineChart,
    List,
    ListChecks,
    ListPlus,
    MapPin,
    MapPinned,
    Package,
    PackageOpen,
    PackagePlus,
    PackageSearch,
    Palette,
    Printer,
    ReceiptText,
    Route,
    Ruler,
    Scale,
    Settings,
    Settings2,
    Shield,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    Shrink,
    SlidersHorizontal,
    Sparkles,
    Stamp,
    Star,
    Store,
    Tag,
    ThumbsUp,
    ToggleLeft,
    TrendingUp,
    Truck,
    Umbrella,
    Users,
    UsersRound,
    Wand2,
    Warehouse,
    Workflow,
    Wrench,
    Zap,
} from 'lucide-react';

export const textileCoreCompanyMenu = (t: (key: string) => string) => [
    {
        name: 'textile-operations',
        title: t('Daily Operations'),
        icon: Factory,
        order: 260,
        children: [
            {
                title: t('Procurement'),
                href: route('textile.procurement.index'),
                capability: 'procurement',
                icon: ShoppingCart,
            },
            {
                title: t('Sales'),
                href: route('textile.sales.index'),
                capability: 'sales',
                icon: ShoppingBag,
            },
            {
                title: t('Manufacturing'),
                href: route('textile.manufacturing.index'),
                capability: 'manufacturing',
                icon: Cog,
            },
            {
                title: t('Quality'),
                href: route('textile.quality.index'),
                capability: 'quality',
                icon: ShieldCheck,
            },
            {
                title: t('Packing'),
                href: route('textile.packing.index'),
                capability: 'sales',
                icon: Package,
                children: [
                    {
                        title: t('Roll Packing'),
                        href: route('textile.packing.index', { section: 'roll-packing' }),
                        capability: 'sales_challan_pod',
                        icon: PackageOpen,
                    },
                    {
                        title: t('Bundle Packing'),
                        href: route('textile.packing.index', { section: 'bundle-packing' }),
                        capability: 'sales_challan_pod',
                        icon: PackagePlus,
                    },
                    {
                        title: t('Bale Packing'),
                        href: route('textile.packing.index', { section: 'bale-packing' }),
                        capability: 'sales_challan_pod',
                        icon: Boxes,
                    },
                    {
                        title: t('Labels'),
                        href: route('textile.packing.index', { section: 'labels' }),
                        capability: 'sales_challan_pod',
                        icon: Tag,
                    },
                ],
            },
            {
                title: t('Dispatch'),
                href: route('textile.dispatch.index'),
                capability: 'sales_allocation_dispatch',
                icon: Truck,
                children: [
                    {
                        title: t('Dispatch Planning'),
                        href: route('textile.dispatch.index', { section: 'planning' }),
                        capability: 'sales_allocation_dispatch',
                        icon: ListChecks,
                    },
                    {
                        title: t('Truck Dispatch'),
                        href: route('textile.dispatch.index', { section: 'planning', mode: 'truck' }),
                        capability: 'sales_allocation_dispatch',
                        icon: Truck,
                    },
                    {
                        title: t('Container Dispatch'),
                        href: route('textile.dispatch.index', { section: 'planning', mode: 'container' }),
                        capability: 'sales_allocation_dispatch',
                        icon: Container,
                    },
                    {
                        title: t('Dispatch Tracking'),
                        href: route('textile.dispatch.index', { section: 'tracking' }),
                        capability: 'sales_dispatch_tracking',
                        icon: MapPin,
                    },
                    {
                        title: t('Delivery Challan'),
                        href: route('textile.sales.index', { section: 'challan-pod' }),
                        capability: 'sales_challan_pod',
                        icon: FileSignature,
                    },
                    {
                        title: t('POD'),
                        href: route('textile.sales.index', { section: 'challan-pod' }),
                        capability: 'sales_challan_pod',
                        icon: Stamp,
                    },
                ],
            },
            {
                title: t('Transport'),
                href: route('textile.transport.index'),
                capability: 'transport_operations',
                icon: Route,
                children: [
                    {
                        title: t('Fuel'),
                        href: route('textile.transport.index', { section: 'fuel' }),
                        capability: 'transport_operations',
                        icon: Fuel,
                    },
                    {
                        title: t('Freight Cost'),
                        href: route('textile.transport.index', { section: 'freight-cost' }),
                        capability: 'transport_operations',
                        icon: Banknote,
                    },
                    {
                        title: t('Vehicle Maintenance'),
                        href: route('textile.transport.index', { section: 'vehicle-maintenance' }),
                        capability: 'transport_operations',
                        icon: Car,
                    },
                ],
            },
            {
                title: t('Maintenance'),
                href: route('textile.maintenance.index'),
                capability: 'maintenance_operations',
                icon: Wrench,
                children: [
                    {
                        title: t('Preventive Maintenance'),
                        href: route('textile.maintenance.index', { section: 'pm' }),
                        capability: 'maintenance_operations',
                        icon: CalendarClock,
                    },
                    {
                        title: t('Breakdowns'),
                        href: route('textile.maintenance.index', { section: 'breakdown' }),
                        capability: 'maintenance_operations',
                        icon: AlertTriangle,
                    },
                    {
                        title: t('Service Schedule'),
                        href: route('textile.maintenance.index', { section: 'service' }),
                        capability: 'maintenance_operations',
                        icon: CalendarCheck,
                    },
                    {
                        title: t('Spare Parts'),
                        href: route('textile.maintenance.index', { section: 'spare-parts' }),
                        capability: 'maintenance_operations',
                        icon: Cog,
                    },
                    {
                        title: t('Maintenance Cost'),
                        href: route('textile.maintenance.index', { section: 'cost' }),
                        capability: 'maintenance_operations',
                        icon: IndianRupee,
                    },
                    {
                        title: t('Machine History'),
                        href: route('textile.maintenance.index', { section: 'history' }),
                        capability: 'maintenance_operations',
                        icon: History,
                    },
                ],
            },
            {
                title: t('Processing'),
                href: route('textile.processing.index'),
                capability: 'processing',
                icon: Workflow,
                children: [
                    {
                        title: t('Internal Processing'),
                        href: route('textile.processing.index', { section: 'internal-processing' }),
                        capability: 'processing_batch',
                        icon: Building2,
                    },
                    {
                        title: t('Yarn Issue to Weaver'),
                        href: route('textile.processing.index', { section: 'job-work-outward' }),
                        capability: 'processing_outward',
                        icon: ArrowUpRight,
                    },
                    {
                        title: t('Processing Batch'),
                        href: route('textile.processing.index', { section: 'processing-batch' }),
                        capability: 'processing_batch',
                        icon: Layers,
                    },
                    {
                        title: t('Dyeing'),
                        href: route('textile.processing.index', { section: 'dyeing' }),
                        capability: 'processing_batch',
                        icon: Droplets,
                    },
                    {
                        title: t('Printing'),
                        href: route('textile.processing.index', { section: 'printing' }),
                        capability: 'processing_batch',
                        icon: Printer,
                    },
                    {
                        title: t('Bleaching'),
                        href: route('textile.processing.index', { section: 'bleaching' }),
                        capability: 'processing_batch',
                        icon: Sparkles,
                    },
                    {
                        title: t('Calendaring'),
                        href: route('textile.processing.index', { section: 'calendaring' }),
                        capability: 'processing_batch',
                        icon: Brush,
                    },
                    {
                        title: t('Compacting'),
                        href: route('textile.processing.index', { section: 'compacting' }),
                        capability: 'processing_batch',
                        icon: Shrink,
                    },
                    {
                        title: t('Finishing'),
                        href: route('textile.processing.index', { section: 'finishing' }),
                        capability: 'processing_batch',
                        icon: Wand2,
                    },
                    {
                        title: t('Shade Card'),
                        href: route('textile.processing.index', { section: 'shade-card' }),
                        capability: 'processing_inward',
                        icon: Palette,
                    },
                    {
                        title: t('Process Cost'),
                        href: route('textile.processing.index', { section: 'process-cost' }),
                        capability: 'processing_batch',
                        icon: Calculator,
                    },
                    {
                        title: t('Job Work Inward'),
                        href: route('textile.processing.index', { section: 'job-work-inward' }),
                        capability: 'processing_inward',
                        icon: ArrowDownLeft,
                    },
                    {
                        title: t('Reconciliation'),
                        href: route('textile.processing.index', { section: 'reconciliation' }),
                        capability: 'processing_reconciliation',
                        icon: Scale,
                    },
                ],
            },
        ],
    },
    {
        name: 'textile-master-setup',
        title: t('Master Setup'),
        icon: SlidersHorizontal,
        order: 261,
        children: [
                    {
                        title: t('Core Setup'),
                        icon: Settings,
                        children: [
                            {
                                title: t('Specifications'),
                                href: route('textile.specifications.index'),
                                icon: Ruler,
                            },
                            {
                                title: t('Unit Conversions'),
                                href: route('textile.unit-conversions.index'),
                                icon: ArrowLeftRight,
                            },
                            {
                                title: t('Route Recipes'),
                                href: route('textile.route-recipes.index'),
                                icon: GitBranch,
                            },
                            {
                                title: t('Quality Profiles'),
                                href: route('textile.quality-profiles.index'),
                                icon: Gauge,
                            },
                            {
                                title: t('Approvals'),
                                href: route('textile.approvals.index'),
                                icon: CheckCheck,
                            },
                            {
                                title: t('Cost Centers'),
                                href: route('textile.cost-centers.index'),
                                icon: Coins,
                            },
                            {
                                title: t('Custom Fields'),
                                href: route('textile.custom-fields.index'),
                                icon: ListPlus,
                            },
                            {
                                title: t('Operating Model'),
                                href: route('textile.operating-policy.index'),
                                icon: ToggleLeft,
                            },
                        ],
                    },
                    {
                        title: t('Manufacturing Source Setup'),
                        icon: Cog,
                        children: [
                            {
                                title: t('Sizing Vendors'),
                                href: route('account.vendors.index', { supplier_type: 'sizing' }),
                                icon: Store,
                            },
                            {
                                title: t('Powerloom Vendors'),
                                href: route('account.vendors.index', { supplier_type: 'powerloom' }),
                                icon: Factory,
                            },
                            {
                                title: t('Source Types'),
                                href: route('textile.master-domains.source-types.index', { domain: 'manufacturing' }),
                                icon: Hash,
                            },
                            {
                                title: t('Source Actions'),
                                href: route('textile.master-domains.source-actions.index', { domain: 'manufacturing' }),
                                icon: Zap,
                            },
                        ],
                    },
                    {
                        title: t('Loom Setup'),
                        icon: Box,
                        children: [
                            {
                                title: t('Machine Types'),
                                href: route('textile.master-domains.machine-types.index', { domain: 'manufacturing' }),
                                icon: Cpu,
                            },
                            {
                                title: t('Shed Types'),
                                href: route('textile.master-domains.shed-types.index', { domain: 'manufacturing' }),
                                icon: Umbrella,
                            },
                            {
                                title: t('Loom Statuses'),
                                href: route('textile.master-domains.loom-statuses.index', { domain: 'manufacturing' }),
                                icon: CircleDot,
                            },
                            {
                                title: t('Breakdown Reasons'),
                                href: route('textile.master-domains.breakdown-reasons.index', { domain: 'manufacturing' }),
                                icon: CircleAlert,
                            },
                            {
                                title: t('Maintenance Types'),
                                href: route('textile.master-domains.maintenance-types.index', { domain: 'manufacturing' }),
                                icon: Hammer,
                            },
                        ],
                    },
                    {
                        title: t('Beam and Cost Setup'),
                        icon: Landmark,
                        children: [
                            {
                                title: t('Cost Types'),
                                href: route('textile.master-domains.cost-types.index', { domain: 'manufacturing' }),
                                icon: BadgeDollarSign,
                            },
                            {
                                title: t('Inspection Results'),
                                href: route('textile.master-domains.inspection-results.index', { domain: 'manufacturing' }),
                                icon: CircleCheckBig,
                            },
                            {
                                title: t('Fabric Defects'),
                                href: route('textile.master-domains.fabric-defects.index', { domain: 'manufacturing' }),
                                icon: CircleX,
                            },
                            {
                                title: t('Fabric Grades'),
                                href: route('textile.master-domains.fabric-grades.index', { domain: 'manufacturing' }),
                                icon: Star,
                            },
                        ],
                    },
                    {
                        title: t('Inventory Setup'),
                        icon: PackageOpen,
                        children: [
                            {
                                title: t('Source Types'),
                                href: route('textile.master-domains.source-types.index', { domain: 'inventory' }),
                                icon: Hash,
                            },
                            {
                                title: t('Source Actions'),
                                href: route('textile.master-domains.source-actions.index', { domain: 'inventory' }),
                                icon: Zap,
                            },
                        ],
                    },
                    {
                        title: t('Sales Setup'),
                        icon: BadgePercent,
                        children: [
                            {
                                title: t('Source Types'),
                                href: route('textile.master-domains.source-types.index', { domain: 'sales' }),
                                icon: Hash,
                            },
                            {
                                title: t('Source Actions'),
                                href: route('textile.master-domains.source-actions.index', { domain: 'sales' }),
                                icon: Zap,
                            },
                        ],
                    },
                    {
                        title: t('Processing Setup'),
                        icon: FlaskRound,
                        children: [
                            {
                                title: t('Source Types'),
                                href: route('textile.master-domains.source-types.index', { domain: 'processing' }),
                                icon: Hash,
                            },
                            {
                                title: t('Source Actions'),
                                href: route('textile.master-domains.source-actions.index', { domain: 'processing' }),
                                icon: Zap,
                            },
                        ],
                    },
                    {
                        title: t('Quality Setup'),
                        icon: Shield,
                        children: [
                            {
                                title: t('Source Types'),
                                href: route('textile.master-domains.source-types.index', { domain: 'quality' }),
                                icon: Hash,
                            },
                            {
                                title: t('Source Actions'),
                                href: route('textile.master-domains.source-actions.index', { domain: 'quality' }),
                                icon: Zap,
                            },
                            {
                                title: t('Inspection Results'),
                                href: route('textile.master-domains.inspection-results.index', { domain: 'quality' }),
                                icon: CircleCheckBig,
                            },
                            {
                                title: t('Fabric Defects'),
                                href: route('textile.master-domains.fabric-defects.index', { domain: 'quality' }),
                                icon: CircleX,
                            },
                        ],
                    },
                    {
                        title: t('Packing Setup'),
                        icon: Barcode,
                        children: [
                            {
                                title: t('Source Types'),
                                href: route('textile.master-domains.source-types.index', { domain: 'packing' }),
                                icon: Hash,
                            },
                            {
                                title: t('Source Actions'),
                                href: route('textile.master-domains.source-actions.index', { domain: 'packing' }),
                                icon: Zap,
                            },
                        ],
                    },
                    {
                        title: t('Dispatch Setup'),
                        icon: MapPinned,
                        children: [
                            {
                                title: t('Source Types'),
                                href: route('textile.master-domains.source-types.index', { domain: 'dispatch' }),
                                icon: Hash,
                            },
                            {
                                title: t('Source Actions'),
                                href: route('textile.master-domains.source-actions.index', { domain: 'dispatch' }),
                                icon: Zap,
                            },
                            {
                                title: t('Truck Numbers'),
                                href: route('textile.master-domains.dispatch-truck-numbers.index', { domain: 'dispatch' }),
                                icon: Truck,
                            },
                            {
                                title: t('Container Numbers'),
                                href: route('textile.master-domains.dispatch-container-numbers.index', { domain: 'dispatch' }),
                                icon: Container,
                            },
                            {
                                title: t('Drivers'),
                                href: route('textile.dispatch-drivers.index'),
                                icon: Contact,
                            },
                            {
                                title: t('Vehicles'),
                                href: route('textile.dispatch-vehicles.index'),
                                icon: Car,
                            },
                            {
                                title: t('Routes'),
                                href: route('textile.dispatch-routes.index'),
                                icon: Route,
                            },
                            {
                                title: t('LR Numbers'),
                                href: route('textile.master-domains.dispatch-lr-numbers.index', { domain: 'dispatch' }),
                                icon: FileText,
                            },
                            {
                                title: t('E-Way Bills'),
                                href: route('textile.master-domains.dispatch-eway-bills.index', { domain: 'dispatch' }),
                                icon: ReceiptText,
                            },
                        ],
                    },
                    {
                        title: t('Transport Setup'),
                        icon: Bus,
                        children: [
                            {
                                title: t('Fuel Types'),
                                href: route('textile.master-domains.fuel-types.index', { domain: 'transport' }),
                                icon: Fuel,
                            },
                            {
                                title: t('Freight Types'),
                                href: route('textile.master-domains.freight-types.index', { domain: 'transport' }),
                                icon: Banknote,
                            },
                            {
                                title: t('Maintenance Types'),
                                href: route('textile.master-domains.maintenance-types.index', { domain: 'transport' }),
                                icon: Wrench,
                            },
                        ],
                    },
                    {
                        title: t('CRM Setup'),
                        icon: Users,
                        children: [
                            {
                                title: t('Customer Categories'),
                                href: route('account.customer-categories.index'),
                                icon: UsersRound,
                            },
                            {
                                title: t('Customer Price List'),
                                href: route('account.customer-price-lists.index'),
                                icon: List,
                            },
                            {
                                title: t('Customer Contacts'),
                                href: route('account.customer-contacts.index'),
                                icon: Contact,
                            },
                            {
                                title: t('Customer Follow Ups'),
                                href: route('account.customer-follow-ups.index'),
                                icon: Bell,
                            },
                            {
                                title: t('Customer Documents'),
                                href: route('account.customer-documents.index'),
                                icon: FolderOpen,
                            },
                        ],
                    },
                    {
                        title: t('Supplier Setup'),
                        icon: Store,
                        children: [
                            {
                                title: t('Transport Vendors'),
                                href: route('account.vendors.index', { supplier_type: 'transport' }),
                                icon: Warehouse,
                            },
                            {
                                title: t('Vendor Ratings'),
                                href: route('account.vendor-ratings.index'),
                                icon: ThumbsUp,
                            },
                            {
                                title: t('Vendor Performance'),
                                href: route('account.vendor-performance.index'),
                                icon: LineChart,
                            },
                        ],
                    },
                    {
                        title: t('Product Setup'),
                        icon: PackageSearch,
                        children: [
                            {
                                title: t('Product Variants'),
                                href: route('product-service.product-master.variants.index'),
                                icon: Copy,
                            },
                            {
                                title: t('Product Images'),
                                href: route('product-service.product-master.images.index'),
                                icon: Image,
                            },
                            {
                                title: t('Product Documents'),
                                href: route('product-service.product-master.documents.index'),
                                icon: FileStack,
                            },
                        ],
                    },
                ],
            },
    {
        name: 'textile-insights',
        title: t('Insights'),
        icon: TrendingUp,
        order: 262,
        children: [
            {
                title: t('Dashboard'),
                href: route('textile.dashboard.index'),
                icon: LayoutDashboard,
            },
            {
                title: t('Logs'),
                href: route('textile.logs.index'),
                icon: FileClock,
            },
            {
                title: t('Costing'),
                href: route('textile.costing.index'),
                icon: Coins,
            },
            {
                title: t('Finance'),
                href: route('textile.finance.index'),
                icon: Banknote,
            },
            {
                title: t('Reports'),
                href: route('textile.reports.index'),
                icon: BarChart3,
            },
        ],
    },
];