<?php

use Illuminate\Support\Facades\Route;
use DigitalFuzed\TextileCore\Http\Controllers\TextileSpecificationController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileMasterDataController;
use DigitalFuzed\TextileCore\Http\Controllers\TextilePartyBranchController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileProcurementController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileSalesController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileManufacturingController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileQualityController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileProcessingController;
use DigitalFuzed\TextileCore\Http\Controllers\TextilePackingController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileDispatchController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileCostingController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileDashboardController;
use DigitalFuzed\TextileCore\Http\Controllers\TextilePaymentController;
use DigitalFuzed\TextileCore\Http\Controllers\TextilePartyController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileApprovalController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileCostCenterController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileCustomFieldController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileOperatingPolicyController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileLogController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileDispatchDriverController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileDispatchVehicleController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileDispatchRouteController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileTransportController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileMaintenanceController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileFinanceController;
use DigitalFuzed\TextileCore\Http\Controllers\TextileReportsController;

Route::middleware(['web', 'auth', 'verified', 'PlanModuleCheck:TextileCore'])->group(function () {
    Route::get('/textile/specifications', [TextileSpecificationController::class, 'index'])->name('textile.specifications.index');
    Route::post('/textile/specifications', [TextileSpecificationController::class, 'store'])->name('textile.specifications.store');
    Route::post('/textile/specifications/update', [TextileSpecificationController::class, 'update'])->name('textile.specifications.update');
    Route::post('/textile/specifications/archive', [TextileSpecificationController::class, 'archive'])->name('textile.specifications.archive');
    Route::get('/textile/quality-profiles', [TextileMasterDataController::class, 'qualityProfiles'])->name('textile.quality-profiles.index');
    Route::post('/textile/quality-profiles', [TextileMasterDataController::class, 'storeQualityProfile'])->name('textile.quality-profiles.store');
    Route::post('/textile/quality-profiles/update', [TextileMasterDataController::class, 'updateQualityProfile'])->name('textile.quality-profiles.update');
    Route::post('/textile/quality-profiles/archive', [TextileMasterDataController::class, 'archiveQualityProfile'])->name('textile.quality-profiles.archive');
    Route::get('/textile/route-recipes', [TextileMasterDataController::class, 'routeRecipes'])->name('textile.route-recipes.index');
    Route::post('/textile/route-recipes', [TextileMasterDataController::class, 'storeRouteRecipe'])->name('textile.route-recipes.store');
    Route::post('/textile/route-recipes/update', [TextileMasterDataController::class, 'updateRouteRecipe'])->name('textile.route-recipes.update');
    Route::post('/textile/route-recipes/archive', [TextileMasterDataController::class, 'archiveRouteRecipe'])->name('textile.route-recipes.archive');
    Route::get('/textile/unit-conversions', [TextileMasterDataController::class, 'unitConversions'])->name('textile.unit-conversions.index');
    Route::post('/textile/unit-conversions', [TextileMasterDataController::class, 'storeUnitConversion'])->name('textile.unit-conversions.store');
    Route::post('/textile/unit-conversions/update', [TextileMasterDataController::class, 'updateUnitConversion'])->name('textile.unit-conversions.update');
    Route::post('/textile/unit-conversions/archive', [TextileMasterDataController::class, 'archiveUnitConversion'])->name('textile.unit-conversions.archive');
    Route::get('/textile/source-types', [TextileMasterDataController::class, 'sourceTypes'])->name('textile.source-types.index');
    Route::post('/textile/source-types', [TextileMasterDataController::class, 'storeSourceType'])->name('textile.source-types.store');
    Route::post('/textile/source-types/update', [TextileMasterDataController::class, 'updateSourceType'])->name('textile.source-types.update');
    Route::post('/textile/source-types/archive', [TextileMasterDataController::class, 'archiveSourceType'])->name('textile.source-types.archive');
    Route::get('/textile/source-actions', [TextileMasterDataController::class, 'sourceActions'])->name('textile.source-actions.index');
    Route::post('/textile/source-actions', [TextileMasterDataController::class, 'storeSourceAction'])->name('textile.source-actions.store');
    Route::post('/textile/source-actions/update', [TextileMasterDataController::class, 'updateSourceAction'])->name('textile.source-actions.update');
    Route::post('/textile/source-actions/archive', [TextileMasterDataController::class, 'archiveSourceAction'])->name('textile.source-actions.archive');
    Route::get('/textile/master-setup/{domain}/source-types', [TextileMasterDataController::class, 'sourceTypesByDomain'])->name('textile.master-domains.source-types.index');
    Route::post('/textile/master-setup/{domain}/source-types', [TextileMasterDataController::class, 'storeSourceTypeByDomain'])->name('textile.master-domains.source-types.store');
    Route::post('/textile/master-setup/{domain}/source-types/update', [TextileMasterDataController::class, 'updateSourceTypeByDomain'])->name('textile.master-domains.source-types.update');
    Route::post('/textile/master-setup/{domain}/source-types/archive', [TextileMasterDataController::class, 'archiveSourceTypeByDomain'])->name('textile.master-domains.source-types.archive');
    Route::get('/textile/master-setup/{domain}/source-actions', [TextileMasterDataController::class, 'sourceActionsByDomain'])->name('textile.master-domains.source-actions.index');
    Route::post('/textile/master-setup/{domain}/source-actions', [TextileMasterDataController::class, 'storeSourceActionByDomain'])->name('textile.master-domains.source-actions.store');
    Route::post('/textile/master-setup/{domain}/source-actions/update', [TextileMasterDataController::class, 'updateSourceActionByDomain'])->name('textile.master-domains.source-actions.update');
    Route::post('/textile/master-setup/{domain}/source-actions/archive', [TextileMasterDataController::class, 'archiveSourceActionByDomain'])->name('textile.master-domains.source-actions.archive');
    Route::get('/textile/machine-types', [TextileMasterDataController::class, 'machineTypes'])->name('textile.machine-types.index');
    Route::post('/textile/machine-types', [TextileMasterDataController::class, 'storeMachineType'])->name('textile.machine-types.store');
    Route::post('/textile/machine-types/update', [TextileMasterDataController::class, 'updateMachineType'])->name('textile.machine-types.update');
    Route::post('/textile/machine-types/archive', [TextileMasterDataController::class, 'archiveMachineType'])->name('textile.machine-types.archive');
    Route::get('/textile/shed-types', [TextileMasterDataController::class, 'shedTypes'])->name('textile.shed-types.index');
    Route::post('/textile/shed-types', [TextileMasterDataController::class, 'storeShedType'])->name('textile.shed-types.store');
    Route::post('/textile/shed-types/update', [TextileMasterDataController::class, 'updateShedType'])->name('textile.shed-types.update');
    Route::post('/textile/shed-types/archive', [TextileMasterDataController::class, 'archiveShedType'])->name('textile.shed-types.archive');
    Route::get('/textile/loom-statuses', [TextileMasterDataController::class, 'loomStatuses'])->name('textile.loom-statuses.index');
    Route::post('/textile/loom-statuses', [TextileMasterDataController::class, 'storeLoomStatus'])->name('textile.loom-statuses.store');
    Route::post('/textile/loom-statuses/update', [TextileMasterDataController::class, 'updateLoomStatus'])->name('textile.loom-statuses.update');
    Route::post('/textile/loom-statuses/archive', [TextileMasterDataController::class, 'archiveLoomStatus'])->name('textile.loom-statuses.archive');
    Route::get('/textile/breakdown-reasons', [TextileMasterDataController::class, 'breakdownReasons'])->name('textile.breakdown-reasons.index');
    Route::post('/textile/breakdown-reasons', [TextileMasterDataController::class, 'storeBreakdownReason'])->name('textile.breakdown-reasons.store');
    Route::post('/textile/breakdown-reasons/update', [TextileMasterDataController::class, 'updateBreakdownReason'])->name('textile.breakdown-reasons.update');
    Route::post('/textile/breakdown-reasons/archive', [TextileMasterDataController::class, 'archiveBreakdownReason'])->name('textile.breakdown-reasons.archive');
    Route::get('/textile/maintenance-types', [TextileMasterDataController::class, 'maintenanceTypes'])->name('textile.maintenance-types.index');
    Route::post('/textile/maintenance-types', [TextileMasterDataController::class, 'storeMaintenanceType'])->name('textile.maintenance-types.store');
    Route::post('/textile/maintenance-types/update', [TextileMasterDataController::class, 'updateMaintenanceType'])->name('textile.maintenance-types.update');
    Route::post('/textile/maintenance-types/archive', [TextileMasterDataController::class, 'archiveMaintenanceType'])->name('textile.maintenance-types.archive');
    Route::get('/textile/cost-types', [TextileMasterDataController::class, 'costTypes'])->name('textile.cost-types.index');
    Route::post('/textile/cost-types', [TextileMasterDataController::class, 'storeCostType'])->name('textile.cost-types.store');
    Route::post('/textile/cost-types/update', [TextileMasterDataController::class, 'updateCostType'])->name('textile.cost-types.update');
    Route::post('/textile/cost-types/archive', [TextileMasterDataController::class, 'archiveCostType'])->name('textile.cost-types.archive');
    Route::get('/textile/inspection-results', [TextileMasterDataController::class, 'inspectionResults'])->name('textile.inspection-results.index');
    Route::post('/textile/inspection-results', [TextileMasterDataController::class, 'storeInspectionResult'])->name('textile.inspection-results.store');
    Route::post('/textile/inspection-results/update', [TextileMasterDataController::class, 'updateInspectionResult'])->name('textile.inspection-results.update');
    Route::post('/textile/inspection-results/archive', [TextileMasterDataController::class, 'archiveInspectionResult'])->name('textile.inspection-results.archive');
    Route::get('/textile/master-setup/{domain}/machine-types', [TextileMasterDataController::class, 'machineTypesByDomain'])->name('textile.master-domains.machine-types.index');
    Route::post('/textile/master-setup/{domain}/machine-types', [TextileMasterDataController::class, 'storeMachineTypeByDomain'])->name('textile.master-domains.machine-types.store');
    Route::post('/textile/master-setup/{domain}/machine-types/update', [TextileMasterDataController::class, 'updateMachineTypeByDomain'])->name('textile.master-domains.machine-types.update');
    Route::post('/textile/master-setup/{domain}/machine-types/archive', [TextileMasterDataController::class, 'archiveMachineTypeByDomain'])->name('textile.master-domains.machine-types.archive');
    Route::get('/textile/master-setup/{domain}/shed-types', [TextileMasterDataController::class, 'shedTypesByDomain'])->name('textile.master-domains.shed-types.index');
    Route::post('/textile/master-setup/{domain}/shed-types', [TextileMasterDataController::class, 'storeShedTypeByDomain'])->name('textile.master-domains.shed-types.store');
    Route::post('/textile/master-setup/{domain}/shed-types/update', [TextileMasterDataController::class, 'updateShedTypeByDomain'])->name('textile.master-domains.shed-types.update');
    Route::post('/textile/master-setup/{domain}/shed-types/archive', [TextileMasterDataController::class, 'archiveShedTypeByDomain'])->name('textile.master-domains.shed-types.archive');
    Route::get('/textile/master-setup/{domain}/loom-statuses', [TextileMasterDataController::class, 'loomStatusesByDomain'])->name('textile.master-domains.loom-statuses.index');
    Route::post('/textile/master-setup/{domain}/loom-statuses', [TextileMasterDataController::class, 'storeLoomStatusByDomain'])->name('textile.master-domains.loom-statuses.store');
    Route::post('/textile/master-setup/{domain}/loom-statuses/update', [TextileMasterDataController::class, 'updateLoomStatusByDomain'])->name('textile.master-domains.loom-statuses.update');
    Route::post('/textile/master-setup/{domain}/loom-statuses/archive', [TextileMasterDataController::class, 'archiveLoomStatusByDomain'])->name('textile.master-domains.loom-statuses.archive');
    Route::get('/textile/master-setup/{domain}/breakdown-reasons', [TextileMasterDataController::class, 'breakdownReasonsByDomain'])->name('textile.master-domains.breakdown-reasons.index');
    Route::post('/textile/master-setup/{domain}/breakdown-reasons', [TextileMasterDataController::class, 'storeBreakdownReasonByDomain'])->name('textile.master-domains.breakdown-reasons.store');
    Route::post('/textile/master-setup/{domain}/breakdown-reasons/update', [TextileMasterDataController::class, 'updateBreakdownReasonByDomain'])->name('textile.master-domains.breakdown-reasons.update');
    Route::post('/textile/master-setup/{domain}/breakdown-reasons/archive', [TextileMasterDataController::class, 'archiveBreakdownReasonByDomain'])->name('textile.master-domains.breakdown-reasons.archive');
    Route::get('/textile/master-setup/{domain}/maintenance-types', [TextileMasterDataController::class, 'maintenanceTypesByDomain'])->name('textile.master-domains.maintenance-types.index');
    Route::post('/textile/master-setup/{domain}/maintenance-types', [TextileMasterDataController::class, 'storeMaintenanceTypeByDomain'])->name('textile.master-domains.maintenance-types.store');
    Route::post('/textile/master-setup/{domain}/maintenance-types/update', [TextileMasterDataController::class, 'updateMaintenanceTypeByDomain'])->name('textile.master-domains.maintenance-types.update');
    Route::post('/textile/master-setup/{domain}/maintenance-types/archive', [TextileMasterDataController::class, 'archiveMaintenanceTypeByDomain'])->name('textile.master-domains.maintenance-types.archive');
    Route::get('/textile/master-setup/{domain}/fuel-types', [TextileMasterDataController::class, 'fuelTypesByDomain'])->name('textile.master-domains.fuel-types.index');
    Route::post('/textile/master-setup/{domain}/fuel-types', [TextileMasterDataController::class, 'storeFuelTypeByDomain'])->name('textile.master-domains.fuel-types.store');
    Route::post('/textile/master-setup/{domain}/fuel-types/update', [TextileMasterDataController::class, 'updateFuelTypeByDomain'])->name('textile.master-domains.fuel-types.update');
    Route::post('/textile/master-setup/{domain}/fuel-types/archive', [TextileMasterDataController::class, 'archiveFuelTypeByDomain'])->name('textile.master-domains.fuel-types.archive');
    Route::get('/textile/master-setup/{domain}/freight-types', [TextileMasterDataController::class, 'freightTypesByDomain'])->name('textile.master-domains.freight-types.index');
    Route::post('/textile/master-setup/{domain}/freight-types', [TextileMasterDataController::class, 'storeFreightTypeByDomain'])->name('textile.master-domains.freight-types.store');
    Route::post('/textile/master-setup/{domain}/freight-types/update', [TextileMasterDataController::class, 'updateFreightTypeByDomain'])->name('textile.master-domains.freight-types.update');
    Route::post('/textile/master-setup/{domain}/freight-types/archive', [TextileMasterDataController::class, 'archiveFreightTypeByDomain'])->name('textile.master-domains.freight-types.archive');
    Route::get('/textile/master-setup/{domain}/cost-types', [TextileMasterDataController::class, 'costTypesByDomain'])->name('textile.master-domains.cost-types.index');
    Route::post('/textile/master-setup/{domain}/cost-types', [TextileMasterDataController::class, 'storeCostTypeByDomain'])->name('textile.master-domains.cost-types.store');
    Route::post('/textile/master-setup/{domain}/cost-types/update', [TextileMasterDataController::class, 'updateCostTypeByDomain'])->name('textile.master-domains.cost-types.update');
    Route::post('/textile/master-setup/{domain}/cost-types/archive', [TextileMasterDataController::class, 'archiveCostTypeByDomain'])->name('textile.master-domains.cost-types.archive');
    Route::get('/textile/master-setup/{domain}/inspection-results', [TextileMasterDataController::class, 'inspectionResultsByDomain'])->name('textile.master-domains.inspection-results.index');
    Route::post('/textile/master-setup/{domain}/inspection-results', [TextileMasterDataController::class, 'storeInspectionResultByDomain'])->name('textile.master-domains.inspection-results.store');
    Route::post('/textile/master-setup/{domain}/inspection-results/update', [TextileMasterDataController::class, 'updateInspectionResultByDomain'])->name('textile.master-domains.inspection-results.update');
    Route::post('/textile/master-setup/{domain}/inspection-results/archive', [TextileMasterDataController::class, 'archiveInspectionResultByDomain'])->name('textile.master-domains.inspection-results.archive');
    Route::get('/textile/master-setup/{domain}/fabric-defects', [TextileMasterDataController::class, 'fabricDefectsByDomain'])->name('textile.master-domains.fabric-defects.index');
    Route::post('/textile/master-setup/{domain}/fabric-defects', [TextileMasterDataController::class, 'storeFabricDefectByDomain'])->name('textile.master-domains.fabric-defects.store');
    Route::post('/textile/master-setup/{domain}/fabric-defects/update', [TextileMasterDataController::class, 'updateFabricDefectByDomain'])->name('textile.master-domains.fabric-defects.update');
    Route::post('/textile/master-setup/{domain}/fabric-defects/archive', [TextileMasterDataController::class, 'archiveFabricDefectByDomain'])->name('textile.master-domains.fabric-defects.archive');
    Route::get('/textile/master-setup/{domain}/fabric-grades', [TextileMasterDataController::class, 'fabricGradesByDomain'])->name('textile.master-domains.fabric-grades.index');
    Route::post('/textile/master-setup/{domain}/fabric-grades', [TextileMasterDataController::class, 'storeFabricGradeByDomain'])->name('textile.master-domains.fabric-grades.store');
    Route::post('/textile/master-setup/{domain}/fabric-grades/update', [TextileMasterDataController::class, 'updateFabricGradeByDomain'])->name('textile.master-domains.fabric-grades.update');
    Route::post('/textile/master-setup/{domain}/fabric-grades/archive', [TextileMasterDataController::class, 'archiveFabricGradeByDomain'])->name('textile.master-domains.fabric-grades.archive');
    Route::get('/textile/master-setup/{domain}/dispatch-truck-numbers', [TextileMasterDataController::class, 'dispatchTruckNumbersByDomain'])->name('textile.master-domains.dispatch-truck-numbers.index');
    Route::post('/textile/master-setup/{domain}/dispatch-truck-numbers', [TextileMasterDataController::class, 'storeDispatchTruckNumberByDomain'])->name('textile.master-domains.dispatch-truck-numbers.store');
    Route::post('/textile/master-setup/{domain}/dispatch-truck-numbers/update', [TextileMasterDataController::class, 'updateDispatchTruckNumberByDomain'])->name('textile.master-domains.dispatch-truck-numbers.update');
    Route::post('/textile/master-setup/{domain}/dispatch-truck-numbers/archive', [TextileMasterDataController::class, 'archiveDispatchTruckNumberByDomain'])->name('textile.master-domains.dispatch-truck-numbers.archive');
    Route::get('/textile/master-setup/{domain}/dispatch-container-numbers', [TextileMasterDataController::class, 'dispatchContainerNumbersByDomain'])->name('textile.master-domains.dispatch-container-numbers.index');
    Route::post('/textile/master-setup/{domain}/dispatch-container-numbers', [TextileMasterDataController::class, 'storeDispatchContainerNumberByDomain'])->name('textile.master-domains.dispatch-container-numbers.store');
    Route::post('/textile/master-setup/{domain}/dispatch-container-numbers/update', [TextileMasterDataController::class, 'updateDispatchContainerNumberByDomain'])->name('textile.master-domains.dispatch-container-numbers.update');
    Route::post('/textile/master-setup/{domain}/dispatch-container-numbers/archive', [TextileMasterDataController::class, 'archiveDispatchContainerNumberByDomain'])->name('textile.master-domains.dispatch-container-numbers.archive');
    Route::get('/textile/master-setup/{domain}/dispatch-lr-numbers', [TextileMasterDataController::class, 'dispatchLrNumbersByDomain'])->name('textile.master-domains.dispatch-lr-numbers.index');
    Route::post('/textile/master-setup/{domain}/dispatch-lr-numbers', [TextileMasterDataController::class, 'storeDispatchLrNumberByDomain'])->name('textile.master-domains.dispatch-lr-numbers.store');
    Route::post('/textile/master-setup/{domain}/dispatch-lr-numbers/update', [TextileMasterDataController::class, 'updateDispatchLrNumberByDomain'])->name('textile.master-domains.dispatch-lr-numbers.update');
    Route::post('/textile/master-setup/{domain}/dispatch-lr-numbers/archive', [TextileMasterDataController::class, 'archiveDispatchLrNumberByDomain'])->name('textile.master-domains.dispatch-lr-numbers.archive');
    Route::get('/textile/master-setup/{domain}/dispatch-eway-bills', [TextileMasterDataController::class, 'dispatchEwayBillsByDomain'])->name('textile.master-domains.dispatch-eway-bills.index');
    Route::post('/textile/master-setup/{domain}/dispatch-eway-bills', [TextileMasterDataController::class, 'storeDispatchEwayBillByDomain'])->name('textile.master-domains.dispatch-eway-bills.store');
    Route::post('/textile/master-setup/{domain}/dispatch-eway-bills/update', [TextileMasterDataController::class, 'updateDispatchEwayBillByDomain'])->name('textile.master-domains.dispatch-eway-bills.update');
    Route::post('/textile/master-setup/{domain}/dispatch-eway-bills/archive', [TextileMasterDataController::class, 'archiveDispatchEwayBillByDomain'])->name('textile.master-domains.dispatch-eway-bills.archive');

    Route::get('/textile/party-branches', [TextilePartyBranchController::class, 'index'])->name('textile.party-branches.index');
    Route::post('/textile/party-branches/assign', [TextilePartyBranchController::class, 'assign'])->name('textile.party-branches.assign');
    Route::post('/textile/party-branches/remove', [TextilePartyBranchController::class, 'remove'])->name('textile.party-branches.remove');

    Route::get('/textile/procurement', [TextileProcurementController::class, 'index'])->name('textile.procurement.index');
    Route::post('/textile/procurement/requisitions', [TextileProcurementController::class, 'storeRequisition'])->name('textile.procurement.requisitions.store');
    Route::post('/textile/procurement/requisitions/approve', [TextileProcurementController::class, 'approveRequisition'])->name('textile.procurement.requisitions.approve');
    Route::delete('/textile/procurement/requisitions/{requisition}', [TextileProcurementController::class, 'destroyRequisition'])->name('textile.procurement.requisitions.destroy');
    Route::post('/textile/procurement/rfqs', [TextileProcurementController::class, 'storeRfq'])->name('textile.procurement.rfqs.store');
    Route::post('/textile/procurement/rfqs/send', [TextileProcurementController::class, 'sendRfq'])->name('textile.procurement.rfqs.send');
    Route::post('/textile/procurement/rfqs/close', [TextileProcurementController::class, 'closeRfq'])->name('textile.procurement.rfqs.close');
    Route::post('/textile/procurement/purchase-orders', [TextileProcurementController::class, 'storePurchaseOrder'])->name('textile.procurement.purchase-orders.store');
    Route::post('/textile/procurement/purchase-orders/approve', [TextileProcurementController::class, 'approvePurchaseOrder'])->name('textile.procurement.purchase-orders.approve');
    Route::post('/textile/procurement/grns', [TextileProcurementController::class, 'storeGrn'])->name('textile.procurement.grns.store');
    Route::post('/textile/procurement/grns/release', [TextileProcurementController::class, 'releaseGrn'])->name('textile.procurement.grns.release');
    Route::post('/textile/procurement/invoices/from-grn', [TextileProcurementController::class, 'createPurchaseInvoiceFromGrn'])->name('textile.procurement.invoices.from-grn');
    Route::post('/textile/procurement/incoming-qc', [TextileProcurementController::class, 'storeIncomingQc'])->name('textile.procurement.incoming-qc.store');
    Route::post('/textile/procurement/incoming-qc/finalize', [TextileProcurementController::class, 'finalizeIncomingQc'])->name('textile.procurement.incoming-qc.finalize');
    Route::post('/textile/procurement/supplier-claims', [TextileProcurementController::class, 'storeSupplierClaim'])->name('textile.procurement.supplier-claims.store');
    Route::post('/textile/procurement/supplier-claims/approve', [TextileProcurementController::class, 'approveSupplierClaim'])->name('textile.procurement.supplier-claims.approve');
    Route::post('/textile/procurement/supplier-claims/settle', [TextileProcurementController::class, 'settleSupplierClaim'])->name('textile.procurement.supplier-claims.settle');

    Route::get('/textile/sales', [TextileSalesController::class, 'index'])->name('textile.sales.index');
    Route::post('/textile/sales/orders', [TextileSalesController::class, 'storeSalesOrder'])->name('textile.sales.orders.store');
    Route::post('/textile/sales/orders/approve', [TextileSalesController::class, 'approveSalesOrder'])->name('textile.sales.orders.approve');
    Route::post('/textile/sales/allocations', [TextileSalesController::class, 'storeAllocation'])->name('textile.sales.allocations.store');
    Route::post('/textile/sales/allocations/release', [TextileSalesController::class, 'releaseAllocation'])->name('textile.sales.allocations.release');
    Route::post('/textile/sales/dispatches', [TextileSalesController::class, 'storeDispatch'])->name('textile.sales.dispatches.store');
    Route::post('/textile/sales/dispatches/release', [TextileSalesController::class, 'releaseDispatch'])->name('textile.sales.dispatches.release');
    Route::post('/textile/sales/challans', [TextileSalesController::class, 'storeChallan'])->name('textile.sales.challans.store');
    Route::post('/textile/sales/challans/approve', [TextileSalesController::class, 'approveChallan'])->name('textile.sales.challans.approve');
    Route::post('/textile/sales/challans/update', [TextileSalesController::class, 'updateChallan'])->name('textile.sales.challans.update');
    Route::post('/textile/sales/challans/pod', [TextileSalesController::class, 'markPod'])->name('textile.sales.challans.pod');
    Route::post('/textile/sales/quotations', [TextileSalesController::class, 'storeQuotation'])->name('textile.sales.quotations.store');
    Route::post('/textile/sales/quotations/{quotation}/update', [TextileSalesController::class, 'updateQuotation'])->name('textile.sales.quotations.update');

    Route::get('/textile/packing', [TextilePackingController::class, 'index'])->name('textile.packing.index');
    Route::post('/textile/packing/rolls', [TextilePackingController::class, 'storeRollPacking'])->name('textile.packing.rolls.store');
    Route::post('/textile/packing/bundles', [TextilePackingController::class, 'storeBundlePacking'])->name('textile.packing.bundles.store');
    Route::post('/textile/packing/bales', [TextilePackingController::class, 'storeBalePacking'])->name('textile.packing.bales.store');
    Route::post('/textile/packing/labels', [TextilePackingController::class, 'storeLabel'])->name('textile.packing.labels.store');
    Route::post('/textile/packing/labels/issue', [TextilePackingController::class, 'issueLabel'])->name('textile.packing.labels.issue');

    Route::get('/textile/dispatch', [TextileDispatchController::class, 'index'])->name('textile.dispatch.index');
    Route::post('/textile/dispatch/plans', [TextileDispatchController::class, 'storeDispatchPlan'])->name('textile.dispatch.plans.store');
    Route::post('/textile/dispatch/plans/approve', [TextileDispatchController::class, 'approveDispatchPlan'])->name('textile.dispatch.plans.approve');
    Route::post('/textile/dispatch/trackings', [TextileDispatchController::class, 'storeDispatchTracking'])->name('textile.dispatch.trackings.store');
    Route::post('/textile/dispatch/trackings/finalize', [TextileDispatchController::class, 'finalizeDispatchTracking'])->name('textile.dispatch.trackings.finalize');
    Route::get('/textile/dispatch-drivers', [TextileDispatchDriverController::class, 'index'])->name('textile.dispatch-drivers.index');
    Route::post('/textile/dispatch-drivers', [TextileDispatchDriverController::class, 'store'])->name('textile.dispatch-drivers.store');
    Route::post('/textile/dispatch-drivers/update', [TextileDispatchDriverController::class, 'update'])->name('textile.dispatch-drivers.update');
    Route::post('/textile/dispatch-drivers/archive', [TextileDispatchDriverController::class, 'archive'])->name('textile.dispatch-drivers.archive');
    Route::get('/textile/dispatch-vehicles', [TextileDispatchVehicleController::class, 'index'])->name('textile.dispatch-vehicles.index');
    Route::post('/textile/dispatch-vehicles', [TextileDispatchVehicleController::class, 'store'])->name('textile.dispatch-vehicles.store');
    Route::post('/textile/dispatch-vehicles/update', [TextileDispatchVehicleController::class, 'update'])->name('textile.dispatch-vehicles.update');
    Route::post('/textile/dispatch-vehicles/archive', [TextileDispatchVehicleController::class, 'archive'])->name('textile.dispatch-vehicles.archive');
    Route::get('/textile/dispatch-routes', [TextileDispatchRouteController::class, 'index'])->name('textile.dispatch-routes.index');
    Route::post('/textile/dispatch-routes', [TextileDispatchRouteController::class, 'store'])->name('textile.dispatch-routes.store');
    Route::post('/textile/dispatch-routes/update', [TextileDispatchRouteController::class, 'update'])->name('textile.dispatch-routes.update');
    Route::post('/textile/dispatch-routes/archive', [TextileDispatchRouteController::class, 'archive'])->name('textile.dispatch-routes.archive');
    Route::get('/textile/transport', [TextileTransportController::class, 'index'])->name('textile.transport.index');
    Route::post('/textile/transport/fuel-entries', [TextileTransportController::class, 'storeFuelEntry'])->name('textile.transport.fuel-entries.store');
    Route::post('/textile/transport/freight-costs', [TextileTransportController::class, 'storeFreightCost'])->name('textile.transport.freight-costs.store');
    Route::post('/textile/transport/vehicle-maintenances', [TextileTransportController::class, 'storeVehicleMaintenance'])->name('textile.transport.vehicle-maintenances.store');
    Route::get('/textile/maintenance', [TextileMaintenanceController::class, 'index'])->name('textile.maintenance.index');
    Route::post('/textile/maintenance/pm-schedules', [TextileMaintenanceController::class, 'storePmSchedule'])->name('textile.maintenance.pm-schedules.store');
    Route::post('/textile/maintenance/breakdowns', [TextileMaintenanceController::class, 'storeBreakdown'])->name('textile.maintenance.breakdowns.store');
    Route::post('/textile/maintenance/service-schedules', [TextileMaintenanceController::class, 'storeServiceSchedule'])->name('textile.maintenance.service-schedules.store');
    Route::post('/textile/maintenance/spare-part-usages', [TextileMaintenanceController::class, 'storeSparePartUsage'])->name('textile.maintenance.spare-part-usages.store');
    Route::post('/textile/maintenance/maintenance-costs', [TextileMaintenanceController::class, 'storeMaintenanceCost'])->name('textile.maintenance.maintenance-costs.store');
    Route::get('/textile/finance', [TextileFinanceController::class, 'index'])->name('textile.finance.index');
    Route::post('/textile/finance/machine-costs', [TextileFinanceController::class, 'storeMachineCost'])->name('textile.finance.machine-costs.store');
    Route::post('/textile/finance/power-costs', [TextileFinanceController::class, 'storePowerCost'])->name('textile.finance.power-costs.store');
    Route::post('/textile/finance/chemical-costs', [TextileFinanceController::class, 'storeChemicalCost'])->name('textile.finance.chemical-costs.store');
    Route::post('/textile/finance/labour-costs', [TextileFinanceController::class, 'storeLabourCost'])->name('textile.finance.labour-costs.store');
    Route::get('/textile/reports', [TextileReportsController::class, 'index'])->name('textile.reports.index');
    Route::get('/textile/reports/export', [TextileReportsController::class, 'export'])->name('textile.reports.export');

    Route::get('/textile/manufacturing', [TextileManufacturingController::class, 'index'])->name('textile.manufacturing.index');
    Route::post('/textile/manufacturing/warp-plans', [TextileManufacturingController::class, 'storeWarpPlan'])->name('textile.manufacturing.warp-plans.store');
    Route::post('/textile/manufacturing/warp-plans/approve', [TextileManufacturingController::class, 'approveWarpPlan'])->name('textile.manufacturing.warp-plans.approve');
    Route::post('/textile/manufacturing/yarn-allocations', [TextileManufacturingController::class, 'storeYarnAllocation'])->name('textile.manufacturing.yarn-allocations.store');
    Route::post('/textile/manufacturing/warp-sheets', [TextileManufacturingController::class, 'storeWarpSheet'])->name('textile.manufacturing.warp-sheets.store');
    Route::post('/textile/manufacturing/warp-productions', [TextileManufacturingController::class, 'storeWarpProduction'])->name('textile.manufacturing.warp-productions.store');
    Route::post('/textile/manufacturing/sizing-recipes', [TextileManufacturingController::class, 'storeSizingRecipe'])->name('textile.manufacturing.sizing-recipes.store');
    Route::post('/textile/manufacturing/chemical-consumptions', [TextileManufacturingController::class, 'storeChemicalConsumption'])->name('textile.manufacturing.chemical-consumptions.store');
    Route::post('/textile/manufacturing/beams/from-yarn-allocation', [TextileManufacturingController::class, 'storeBeamFromYarnAllocation'])->name('textile.manufacturing.beams.from-yarn-allocation');
    Route::post('/textile/manufacturing/beams/from-sizing-recipe', [TextileManufacturingController::class, 'storeBeamFromSizingRecipe'])->name('textile.manufacturing.beams.from-sizing-recipe');
    Route::post('/textile/manufacturing/beam-issues', [TextileManufacturingController::class, 'storeBeamIssue'])->name('textile.manufacturing.beam-issues.store');
    Route::post('/textile/manufacturing/beam-returns', [TextileManufacturingController::class, 'storeBeamReturn'])->name('textile.manufacturing.beam-returns.store');
    Route::post('/textile/manufacturing/beam-inspections', [TextileManufacturingController::class, 'storeBeamInspection'])->name('textile.manufacturing.beam-inspections.store');
    Route::post('/textile/manufacturing/beam-costs', [TextileManufacturingController::class, 'storeBeamCost'])->name('textile.manufacturing.beam-costs.store');
    Route::post('/textile/manufacturing/loom-masters', [TextileManufacturingController::class, 'storeLoomMaster'])->name('textile.manufacturing.loom-masters.store');
    Route::post('/textile/manufacturing/loom-breakdowns', [TextileManufacturingController::class, 'storeLoomBreakdown'])->name('textile.manufacturing.loom-breakdowns.store');
    Route::post('/textile/manufacturing/loom-maintenances', [TextileManufacturingController::class, 'storeLoomMaintenance'])->name('textile.manufacturing.loom-maintenances.store');
    Route::post('/textile/manufacturing/machine-plans', [TextileManufacturingController::class, 'storeMachinePlan'])->name('textile.manufacturing.machine-plans.store');
    Route::post('/textile/manufacturing/production-calendars', [TextileManufacturingController::class, 'storeProductionCalendar'])->name('textile.manufacturing.production-calendars.store');
    Route::post('/textile/manufacturing/capacity-plans', [TextileManufacturingController::class, 'storeCapacityPlan'])->name('textile.manufacturing.capacity-plans.store');
    Route::post('/textile/manufacturing/shift-plans', [TextileManufacturingController::class, 'storeShiftPlan'])->name('textile.manufacturing.shift-plans.store');
    Route::post('/textile/manufacturing/material-plans', [TextileManufacturingController::class, 'storeMaterialPlan'])->name('textile.manufacturing.material-plans.store');
    Route::post('/textile/manufacturing/production-schedules', [TextileManufacturingController::class, 'storeProductionSchedule'])->name('textile.manufacturing.production-schedules.store');
    Route::post('/textile/manufacturing/beams', [TextileManufacturingController::class, 'storeBeam'])->name('textile.manufacturing.beams.store');
    Route::post('/textile/manufacturing/beams/approve', [TextileManufacturingController::class, 'approveBeam'])->name('textile.manufacturing.beams.approve');
    Route::post('/textile/manufacturing/batches', [TextileManufacturingController::class, 'storeProductionBatch'])->name('textile.manufacturing.batches.store');
    Route::post('/textile/manufacturing/batches/release', [TextileManufacturingController::class, 'releaseProductionBatch'])->name('textile.manufacturing.batches.release');
    Route::post('/textile/manufacturing/production-assignments', [TextileManufacturingController::class, 'storeProductionAssignment'])->name('textile.manufacturing.production-assignments.store');
    Route::post('/textile/manufacturing/weaving-output', [TextileManufacturingController::class, 'storeWeavingOutput'])->name('textile.manufacturing.weaving-output.store');
    Route::post('/textile/manufacturing/shift-productions', [TextileManufacturingController::class, 'storeShiftProduction'])->name('textile.manufacturing.shift-productions.store');
    Route::post('/textile/manufacturing/takha-entries', [TextileManufacturingController::class, 'storeTakhaEntry'])->name('textile.manufacturing.takha-entries.store');
    Route::post('/textile/manufacturing/loom-efficiencies', [TextileManufacturingController::class, 'storeLoomEfficiency'])->name('textile.manufacturing.loom-efficiencies.store');
    Route::post('/textile/manufacturing/operator-efficiencies', [TextileManufacturingController::class, 'storeOperatorEfficiency'])->name('textile.manufacturing.operator-efficiencies.store');
    Route::post('/textile/manufacturing/machine-downtimes', [TextileManufacturingController::class, 'storeMachineDowntime'])->name('textile.manufacturing.machine-downtimes.store');
    Route::post('/textile/manufacturing/production-costs', [TextileManufacturingController::class, 'storeProductionCost'])->name('textile.manufacturing.production-costs.store');
    Route::post('/textile/manufacturing/grey-fabric-rolls', [TextileManufacturingController::class, 'storeGreyFabricRoll'])->name('textile.manufacturing.grey-fabric-rolls.store');
    Route::post('/textile/manufacturing/grey-fabric-rolls/update', [TextileManufacturingController::class, 'updateGreyFabricRoll'])->name('textile.manufacturing.grey-fabric-rolls.update');
    Route::post('/textile/manufacturing/waste', [TextileManufacturingController::class, 'storeWaste'])->name('textile.manufacturing.waste.store');
    Route::post('/textile/manufacturing/rework', [TextileManufacturingController::class, 'storeRework'])->name('textile.manufacturing.rework.store');

    Route::get('/textile/quality', [TextileQualityController::class, 'index'])->name('textile.quality.index');
    Route::post('/textile/quality/inspections', [TextileQualityController::class, 'storeInspection'])->name('textile.quality.inspections.store');
    Route::post('/textile/quality/inspections/finalize', [TextileQualityController::class, 'finalizeInspection'])->name('textile.quality.inspections.finalize');
    Route::post('/textile/quality/lots/hold', [TextileQualityController::class, 'holdLot'])->name('textile.quality.lots.hold');
    Route::post('/textile/quality/lots/release', [TextileQualityController::class, 'releaseLot'])->name('textile.quality.lots.release');
    Route::post('/textile/quality/certificates', [TextileQualityController::class, 'storeCertificate'])->name('textile.quality.certificates.store');
    Route::post('/textile/quality/certificates/issue', [TextileQualityController::class, 'issueCertificate'])->name('textile.quality.certificates.issue');

    Route::get('/textile/processing', [TextileProcessingController::class, 'index'])->name('textile.processing.index');
    Route::post('/textile/processing/outward', [TextileProcessingController::class, 'storeOutward'])->name('textile.processing.outward.store');
    Route::post('/textile/processing/outward/release', [TextileProcessingController::class, 'releaseOutward'])->name('textile.processing.outward.release');
    Route::post('/textile/processing/batches', [TextileProcessingController::class, 'storeBatch'])->name('textile.processing.batches.store');
    Route::post('/textile/processing/batches/release', [TextileProcessingController::class, 'releaseBatch'])->name('textile.processing.batches.release');
    Route::post('/textile/processing/inward', [TextileProcessingController::class, 'storeInward'])->name('textile.processing.inward.store');
    Route::post('/textile/processing/inward/finalize', [TextileProcessingController::class, 'finalizeInward'])->name('textile.processing.inward.finalize');
    Route::post('/textile/processing/reconcile', [TextileProcessingController::class, 'reconcile'])->name('textile.processing.reconcile');
    Route::post('/textile/processing/internal-processing', [TextileProcessingController::class, 'storeInternalProcessing'])->name('textile.processing.internal-processing.store');
    Route::post('/textile/processing/dyeing', [TextileProcessingController::class, 'storeDyeing'])->name('textile.processing.dyeing.store');
    Route::post('/textile/processing/printing', [TextileProcessingController::class, 'storePrinting'])->name('textile.processing.printing.store');
    Route::post('/textile/processing/bleaching', [TextileProcessingController::class, 'storeBleaching'])->name('textile.processing.bleaching.store');
    Route::post('/textile/processing/calendaring', [TextileProcessingController::class, 'storeCalendaring'])->name('textile.processing.calendaring.store');
    Route::post('/textile/processing/compacting', [TextileProcessingController::class, 'storeCompacting'])->name('textile.processing.compacting.store');
    Route::post('/textile/processing/finishing', [TextileProcessingController::class, 'storeFinishing'])->name('textile.processing.finishing.store');
    Route::post('/textile/processing/shade-cards', [TextileProcessingController::class, 'storeShadeCard'])->name('textile.processing.shade-cards.store');
    Route::post('/textile/processing/process-costs', [TextileProcessingController::class, 'storeProcessCost'])->name('textile.processing.process-costs.store');

    Route::get('/textile/costing', [TextileCostingController::class, 'index'])->name('textile.costing.index');
    Route::post('/textile/costing/entries', [TextileCostingController::class, 'storeCostingEntry'])->name('textile.costing.entries.store');
    Route::post('/textile/costing/entries/finalize', [TextileCostingController::class, 'finalizeCostingEntry'])->name('textile.costing.entries.finalize');
    Route::get('/textile/cost-centers', [TextileCostCenterController::class, 'index'])->name('textile.cost-centers.index');
    Route::post('/textile/cost-centers', [TextileCostCenterController::class, 'store'])->name('textile.cost-centers.store');
    Route::post('/textile/cost-centers/update', [TextileCostCenterController::class, 'update'])->name('textile.cost-centers.update');
    Route::post('/textile/cost-centers/archive', [TextileCostCenterController::class, 'archive'])->name('textile.cost-centers.archive');
    Route::get('/textile/custom-fields', [TextileCustomFieldController::class, 'index'])->name('textile.custom-fields.index');
    Route::post('/textile/custom-fields', [TextileCustomFieldController::class, 'store'])->name('textile.custom-fields.store');
    Route::post('/textile/custom-fields/update', [TextileCustomFieldController::class, 'update'])->name('textile.custom-fields.update');
    Route::post('/textile/custom-fields/archive', [TextileCustomFieldController::class, 'archive'])->name('textile.custom-fields.archive');
    Route::get('/textile/operating-policy', [TextileOperatingPolicyController::class, 'index'])->name('textile.operating-policy.index');
    Route::post('/textile/operating-policy', [TextileOperatingPolicyController::class, 'update'])->name('textile.operating-policy.update');

    Route::get('/textile/dashboard', [TextileDashboardController::class, 'index'])->name('textile.dashboard.index');
    Route::get('/textile/logs', [TextileLogController::class, 'index'])->name('textile.logs.index');

    Route::get('/textile/payments', [TextilePaymentController::class, 'index'])->name('textile.payments.index');
    Route::post('/textile/payments/credit', [TextilePaymentController::class, 'updateCredit'])->name('textile.payments.credit.update');
    Route::post('/textile/payments/reminders', [TextilePaymentController::class, 'sendReminders'])->name('textile.payments.reminders.send');

    Route::get('/textile/parties', [TextilePartyController::class, 'index'])->name('textile.parties.index');

    Route::get('/textile/approvals', [TextileApprovalController::class, 'index'])->name('textile.approvals.index');
    Route::post('/textile/approvals/rules', [TextileApprovalController::class, 'storeRule'])->name('textile.approvals.rules.store');
    Route::post('/textile/approvals/decisions', [TextileApprovalController::class, 'storeDecision'])->name('textile.approvals.decisions.store');
});
